---
- name: Include distribution specific tasks
  ansible.builtin.include_tasks: "setup-{{ ansible_distribution | lower }}.yml"

- name: Ensure docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
