---

- include_tasks: "setup-{{ ansible_distribution | lower }}.yml"

- name: Add ansible user to docker group
  ansible.builtin.user:
    name: debian
    groups: docker
    append: yes
  become: yes

# Add portainer_agent

# docker network create \
# --driver overlay \
#   portainer_agent_network

# docker service create \
#   --name portainer_agent \
#   --network portainer_agent_network \
#   -p 9001:9001/tcp \
#   --mode global \
#   --constraint 'node.platform.os == linux' \
#   --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
#   --mount type=bind,src=//var/lib/docker/volumes,dst=/var/lib/docker/volumes \
#   portainer/agent:2.15.1

# - name: Create portainer agent
  

