---
- name: Install docker prerequs
  ansible.builtin.apt:
    name: ca-certificates
    state: present
    update_cache: true

- name: Create keys directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0o755"
  tags: repository

- name: Add docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0o644"
  tags: repository

- name: Set architecture fact
  when: docker_arch is not defined
  tags: repository
  block:
    - name: Architecture amd64
      ansible.builtin.set_fact:
        docker_arch: amd64
      when: ansible_architecture == "x86_64"

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  tags: repository

- name: Update repository and install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true
# - name: Install ansible docker prerequisites
#   ansible.builtin.apt:
#     pkg:
#       - python3-docker
#       - python3-requests
#     state: present
